# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/117LUer1kVLMfQpZpGOn-bCEC8udMMCL5
"""

import warnings
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
#Model seç
from sklearn.svm import SVC
svc_model=SVC(kernel='linear')
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns



warnings.filterwarnings('ignore')
df=pd.read_csv("/content/drive/MyDrive/Tr_titanik.csv")
#Kullanılmayacak özelliklerin kaldırılması
df=df.drop(["Adi","Bilet_numarasi","Yolcu_id","Kabin"],axis=1)
#Eksik veri bulunan örnekleri sil
df.dropna(inplace=True)
#Cinsiyeti değerini sayısal yapıya çevir
df.Cinsiyeti.replace(["kadın","erkek"],[0,1],inplace=True)
#Liman sütununun kukla değişkenlere dönüştürülmesi
dummies=pd.get_dummies(df["Liman"])
df=pd.concat([df,dummies],axis=1)
df=df.drop(['Liman','S'],axis=1)
y=df["Kurtuldu"]#sonuç Dataframe'ine kurtuldu bilgisini atadık ama X dataframe den çıkardık.
X=df.drop(["Kurtuldu"],axis=1)
sns.countplot(x="Kurtuldu",hue='seyahat_sinifi',data=df)#Kurtuldu ve kurtulamadı grafiği
#0 Kurtulamadı 1 Kurtuldu Görstermektedir. Bu kazadan kadınların daha çok kurtulduğunu görüyoruz.
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
svc_model.fit(X_train,y_train)
y_pred=svc_model.predict(X_test)
#confusion matrisi hesabı
cm=confusion_matrix(y_test,y_pred)
#confusion görselleştirme
fig,ax=plt.subplots(figsize=(8,6))
sns.heatmap(cm,annot=True,cmap="Blues",ax=ax,fmt='d',annot_kws={"size":12})
ax.set_xlabel("Tahmin edilen sınıf",fontsize=14)
ax.set_ylabel("Gerçek sınıf",fontsize=14)
ax.set_title('Confusion Matrisi',fontsize=16)
print("Aşağıdaki özellikleri giriniz")
ozellik=[]
ozellik.append(int(input("Seyahat Sınıfı                [1-3] :  ")))
ozellik.append(int(input("Cinsiyet          [Kadın:0/Erkek:1] :  ")))
ozellik.append(int(input("Yaşı                                :  ")))
ozellik.append(int(input("Gemideki kardeş/eş sayısı           :  ")))
ozellik.append(int(input("Gemideki ebeveyn/çocuk sayısı       :  ")))
ozellik.append(int(input("Bilet ücreti               [30-500] :  ")))
ozellik.append(int(input("C Kabin yolcusu mu [Hayır:0/Evet:1] :  ")))
ozellik.append(int(input("Q Kabin yolcusu mu [Hayır:0/Evet:1] :  ")))
print("**********************************")
print(ozellik)
kurtuldu=svc_model.predict([ozellik])
print("**********************************")

if kurtuldu==1:
  print("[ Kazadan kurtulmuş olabilir ]")
else:
  print("[ Kazadan kurtulamamış olması muhtemel, ilgili kurumlara başvurmanız tavsiye edilir. ]")